@startuml
!include style.puml

title OORMS:\n[Create Bills] Button in Table UI - Sequence Diagram


actor Server as server

participant "view:\nServerView" as view
participant "controller:\nTableController" as controller



server -> view : [Create Bills] button is pressed
view -> controller : make_bills(printer_window)
controller --> "new_controller:\nPaymentController" ** : (view, restaurant, table, printer_window)
controller -> view : set_controller(new_controller)
controller -> view : update();


note left
    ...calls self.controller.
    create_ui()...
    We know how it cont-
    inues from here.
end note


@enduml