@startuml
!include style.puml

title OORMS:\n[DELETE] Button in Bill UI - Sequence Diagram


actor Server as server

participant "view:\nServerView" as view
participant "controller:\nBillController" as controller
participant "bill:\nBill" as bill
participant "[['temporary']]\n this_order:\nOrder" as this_order
participant "table:\nTable" as table
participant "_bills:\nlist[Bill]" as bills



server -> view : [DELETE] button is pressed
view -> controller : delete_bill()

controller -> bill : delete()

alt bill.status == PAID

    bill -> bill : print error : "Can't delete a paid bill"
    bill -> controller : return flag = False

else else

    loop this_order in list[added seat orders of bill]

        bill -> this_order : set_unassigned()
        this_order -> this_order : status = UNASSIGNED

    end

    bill -> bill : ____del____()
    bill -> table : remove_bill(bill)
    table -> bills : remove(bill)

    bill -> controller : return flag = (flag == True)

end



alt bill deletion successful (flag == True)

    controller -> controller : exit_pressed()
    controller --> "new_controller:\nPaymentController" ** : (view, restaurant, table, printer)
    controller -> view : set_controller(new_controller)
    controller -> view : update();

end


note left
    ...calls self.controller.
    create_ui()...
    We know how it cont-
    inues from here.
end note


@enduml